//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioPlayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist1
    {
        public int ID { get; set; }
        public string PID { get; set; }
        public string Name { get; set; }
        public string UID { get; set; }
        public string Title { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<float> OrderSort { get; set; }
        public string Filetype { get; set; }
        public string Command { get; set; }
        public Nullable<System.TimeSpan> Cmd_Parameter { get; set; }
    }
}
